//! Identifiers. `ProgramId` is a UUID wrapper — distinct nominal type
//! avoids mixing arbitrary UUIDs with program ids elsewhere.

use std::fmt;
use std::str::FromStr;

use serde::{Deserialize, Serialize};
use thiserror::Error;
use uuid::Uuid;

/// Unique identifier for a program. Generated by the daemon on submit if the
/// client did not provide one.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct ProgramId(Uuid);

impl ProgramId {
    /// Generate a fresh random v4 program id.
    #[must_use]
    pub fn new() -> Self {
        Self(Uuid::new_v4())
    }

    /// Expose the underlying UUID. Useful for logging only — prefer `Display`.
    #[must_use]
    pub fn as_uuid(&self) -> Uuid {
        self.0
    }
}

impl Default for ProgramId {
    fn default() -> Self {
        Self::new()
    }
}

impl fmt::Display for ProgramId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(f)
    }
}

/// Error parsing a `ProgramId` from a string.
#[derive(Debug, Error)]
#[error("invalid program id: {0}")]
pub struct ProgramIdParseError(#[from] uuid::Error);

impl FromStr for ProgramId {
    type Err = ProgramIdParseError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        Ok(Self(Uuid::parse_str(s)?))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn fresh_ids_are_unique() {
        let a = ProgramId::new();
        let b = ProgramId::new();
        assert_ne!(a, b);
    }

    #[test]
    fn display_parse_roundtrip() {
        let a = ProgramId::new();
        let s = a.to_string();
        let b: ProgramId = s.parse().unwrap();
        assert_eq!(a, b);
    }

    #[test]
    fn parse_rejects_garbage() {
        let e = "not a uuid".parse::<ProgramId>();
        assert!(e.is_err());
    }

    #[test]
    fn serde_transparent_wraps_uuid() {
        let a = ProgramId::new();
        let j = serde_json::to_string(&a).unwrap();
        // Transparent: serialized as a bare string, not as {"0": "..."}
        assert!(j.starts_with('"') && j.ends_with('"'), "got: {j}");
        let back: ProgramId = serde_json::from_str(&j).unwrap();
        assert_eq!(back, a);
    }
}
